// ============================================================================
// mock-data.ts — jeu de données factices pour développer l'UI sans backend.
//
// ⚠️ À SUPPRIMER / remplacer par de vrais appels `services/*.service.ts`
// une fois l'API branchée. Centraliser ici évite de disperser des données
// en dur dans chaque page.
// ============================================================================

import type { AnnonceCardProps } from "@/components/cards/AnnonceCard";
import type { EmploiCardProps } from "@/components/cards/EmploiCard";
import type { ServiceCardProps } from "@/components/cards/ServiceCard";
import type { BoutiqueCardProps } from "@/components/cards/BoutiqueCard";
import { Briefcase, Home, Shirt, Smartphone, Sofa, Wrench } from "lucide-react";
// lib/mock-data.ts

export const CATEGORIES = [
  { slug: "auto-moto",          label: "Auto & Moto",              icon: "Car" },
  { slug: "telephones",         label: "Téléphones Mobiles",       icon: "Smartphone" },
  { slug: "hi-tech",            label: "Hi-Tech",                  icon: "Monitor" },
  { slug: "meubles",            label: "Meubles & Électroménagers",icon: "Sofa" },
  { slug: "immobilier",         label: "Immobilier",               icon: "Home" },
  { slug: "animaux",            label: "Animaux",                  icon: "PawPrint" },
  { slug: "mode",               label: "Mode",                     icon: "Shirt" },
  { slug: "beaute",             label: "Beauté et bien être",      icon: "Sparkles" },
  { slug: "emploi",             label: "Offres d'emploi",          icon: "Briefcase" },
  { slug: "services",           label: "Services",                 icon: "Wrench" },
  { slug: "apprentissage",      label: "Apprentissage",            icon: "GraduationCap" },
  { slug: "evenements",         label: "Evénements",               icon: "Calendar" },
  { slug: "demande-emploi",     label: "Demande d'emploi",         icon: "UserSearch" },
  { slug: "dons",               label: "Dons",                     icon: "Gift" },
  { slug: "librairie",          label: "Librairie",                icon: "BookOpen" },
  { slug: "restaurant",         label: "Restaurant et Alimentation",icon: "UtensilsCrossed" },
  { slug: "autre",              label: "Autre",                    icon: "LayoutGrid" },
] as const;

export const ANNONCES: AnnonceCardProps[] = [
  {
    id: "a1",
    titre: "iPhone 14 Pro Max 256Go — comme neuf",
    prix: 485_000,
    image: "https://dealtoo.s3.eu-west-3.amazonaws.com/files/production/CI/23560/posts/1785185819971.png",
    localisation: "Cocody, Abidjan",
    vues: 1240,
    vendeur: "TechStore CI",
    negociable: true,
    certifie: true,
  },
  {
    id: "a2",
    titre: "Canapé d'angle en cuir véritable, 6 places",
    prix: 320_000,
    image: "https://dealtoo.s3.eu-west-3.amazonaws.com/files/production/CI/23560/posts/1784904842943.png",
    localisation: "Marcory, Abidjan",
    vues: 356,
    vendeur: "Déco Ivoire",
    livraisonGratuite: true,
  },
  {
    id: "a3",
    titre: "Polo Lacoste édition croco spécial",
    prix: 30_000,
    image: "https://dealtoo.s3.eu-west-3.amazonaws.com/files/production/CI/23560/posts/1784904842943.png",
    localisation: "Plateau, Abidjan",
    vues: 156,
    vendeur: "Lang George",
    negociable: true,
  },
  {
    id: "a4",
    titre: "Terrain 600m² titré, proche autoroute",
    prix: 15_000_000,
    image: "https://dealtoo.s3.eu-west-3.amazonaws.com/files/production/CI/23560/posts/1784904842943.png",
    localisation: "Bingerville",
    vues: 892,
    vendeur: "Immo Plus CI",
    certifie: true,
  },
  {
    id: "a5",
    titre: "Toyota RAV4 2021 — Boîte Automatique",
    prix: 14_500_000,
    image: "https://dealtoo.s3.eu-west-3.amazonaws.com/files/production/CI/23560/posts/1784904842943.png",
    localisation: "Zone 4, Marcory",
    vues: 2105,
    vendeur: "Auto Selection",
    certifie: true,
    negociable: true,
  },
  {
    id: "a6",
    titre: "MacBook Pro M2 16\" 512Go — Gris Sidéral",
    prix: 1_250_000,
    image: "https://dealtoo.s3.eu-west-3.amazonaws.com/files/production/CI/23755/posts/1785437785483.jpg",
    localisation: "Deux Plateaux, Cocody",
    vues: 640,
    vendeur: "iZone Abidjan",
    certifie: true,
    livraisonGratuite: true,
  },
  {
    id: "a7",
    titre: "Appartement 3 pièces meublé — Vue Lagune",
    prix: 85_000, // prix par nuit / jour
    image: "https://dealtoo.s3.eu-west-3.amazonaws.com/files/production/CI/23742/posts/1785410547696.jpg",
    localisation: "Biétry, Marcory",
    vues: 1890,
    vendeur: "Residence Prestige",
    certifie: true,
  },
  {
    id: "a8",
    titre: "PlayStation 5 Édition Standard + 2 Manettes",
    prix: 360_000,
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600",
    localisation: "Yopougon, Abidjan",
    vues: 430,
    vendeur: "Gamer Zone",
    negociable: true,
  },
  {
    id: "a9",
    titre: "Paire de Nike Air Force 1 '07 — Pointure 42",
    prix: 45_000,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600",
    localisation: "Riviera 3, Cocody",
    vues: 210,
    vendeur: "Sneakers Lab",
    livraisonGratuite: true,
  },
  {
    id: "10",
    titre: "Smart TV Samsung 55\" 4K UHD Smart ThinQ",
    prix: 280_000,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600",
    localisation: "Angré, Abidjan",
    vues: 780,
    vendeur: "Electro Discount",
    certifie: true,
    negociable: true,
  },
];

export const EMPLOIS: EmploiCardProps[] = [
  {
    id: "e1",
    poste: "Développeur Full-Stack Next.js",
    entreprise: "Chrysostomedev Studio",
    logo: "https://api.dicebear.com/7.x/initials/svg?seed=CD",
    localisation: "Cocody, Abidjan (Hybride)",
    typeContrat: "Freelance",
    salaireMin: 400_000,
    salaireMax: 700_000,
    tags: ["Next.js", "TypeScript", "Tailwind"],
    datePublication: new Date(Date.now() - 1000 * 60 * 60 * 5),
    urgent: true,
  },
  {
    id: "e2",
    poste: "UI/UX Designer Senior",
    entreprise: "Koro Digital",
    logo: "https://api.dicebear.com/7.x/initials/svg?seed=KD",
    localisation: "Plateau, Abidjan",
    typeContrat: "CDI",
    salaireMin: 500_000,
    salaireMax: 850_000,
    tags: ["Figma", "Wireframing", "Design System"],
    datePublication: new Date(Date.now() - 1000 * 60 * 60 * 12),
    urgent: false,
  },
  {
    id: "e3",
    poste: "Développeur Backend Laravel / PHP",
    entreprise: "TechIvoire Systems",
    logo: "https://api.dicebear.com/7.x/initials/svg?seed=TS",
    localisation: "Marcory, Abidjan",
    typeContrat: "CDI",
    salaireMin: 450_000,
    salaireMax: 750_000,
    tags: ["Laravel", "MySQL", "REST API"],
    datePublication: new Date(Date.now() - 1000 * 60 * 60 * 24),
    urgent: true,
  },
  {
    id: "e4",
    poste: "Community Manager & Social Media",
    entreprise: "Radio Grâce-Espoir",
    logo: "https://api.dicebear.com/7.x/initials/svg?seed=RG",
    localisation: "Abidjan",
    typeContrat: "CDD",
    salaireMin: 180_000,
    salaireMax: 300_000,
    tags: ["Réseaux sociaux", "Canva", "Montage"],
    datePublication: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    urgent: false,
  },
  {
    id: "e5",
    poste: "Ingénieur Réseaux & Sécurité Systems",
    entreprise: "Abidjan Data Cloud",
    logo: "https://api.dicebear.com/7.x/initials/svg?seed=AD",
    localisation: "Zone 4, Marcory",
    typeContrat: "CDI",
    salaireMin: 600_000,
    salaireMax: 1_000_000,
    tags: ["Cisco", "VLAN", "Firewall", "Linux"],
    datePublication: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
    urgent: false,
  },
  {
    id: "e6",
    poste: "Commercial Terrain B2B",
    entreprise: "Ivoire Import-Export",
    logo: "https://api.dicebear.com/7.x/initials/svg?seed=II",
    localisation: "Treichville, Abidjan",
    typeContrat: "CDD",
    salaireMin: 200_000,
    salaireMax: 400_000,
    tags: ["Vente", "Prospection", "Négociation"],
    datePublication: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4),
    urgent: true,
  },
  {
    id: "e7",
    poste: "Développeur Mobile React Native / Expo",
    entreprise: "Tchôlô Apps",
    logo: "https://www.pexels.com/fr-fr/photo/businessman-homme-d-affaires-bureau-travailler-12902862/",
    localisation: "Télétravail (Abidjan)",
    typeContrat: "Freelance",
    salaireMin: 350_000,
    salaireMax: 600_000,
    tags: ["React Native", "Expo", "Android", "iOS"],
    datePublication: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
    urgent: false,
  },
  {
    id: "e8",
    poste: "Comptable & Gestionnaire de Paie",
    entreprise: "Cabinet Conseil Finance",
    logo: "https://api.dicebear.com/7.x/initials/svg?seed=CF",
    localisation: "Angré, Cocody",
    typeContrat: "CDI",
    salaireMin: 350_000,
    salaireMax: 550_000,
    tags: ["Comptabilité", "SYSCOHADA", "Excel"],
    datePublication: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6),
    urgent: false,
  },
];
export const SERVICES: ServiceCardProps[] = [
  {
    titre: "Création de logo & identité visuelle",
    prestataire: "Aïcha Koné",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aicha",
    note: 4.9,
    nombreAvis: 87,
    categorie: "Design",
    tarifDepart: 25_000,
    localisation: "Abidjan · à distance",
    disponible: true,
  },
  {
    titre: "Réparation plomberie à domicile",
    prestataire: "Yao Plomberie",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Yao",
    note: 4.6,
    nombreAvis: 132,
    categorie: "Maison",
    tarifDepart: 10_000,
    localisation: "Yopougon",
  },
];

export const BOUTIQUES: BoutiqueCardProps[] = [
  {
    slug: "techstore-ci",
    nom: "TechStore CI",
    logo: "https://api.dicebear.com/7.x/initials/svg?seed=TS",
    couverture: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800",
    niveau: 24,
    note: 4.8,
    nombreProduits: 156,
  },
  {
    slug: "deco-ivoire",
    nom: "Déco Ivoire",
    logo: "https://api.dicebear.com/7.x/initials/svg?seed=DI",
    couverture: "https://www.pexels.com/fr-fr/photo/villa-de-luxe-avec-piscine-a-debordement-dans-un-cadre-pittoresque-35069535/",
    niveau: 12,
    note: 4.5,
    nombreProduits: 43,
  },
];